"""initial schema

Revision ID: b2feed08276f
Revises: 
Create Date: 2026-06-26 21:49:10.072576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2feed08276f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('moneda', sa.String(), nullable=False),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('icono', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ratio_default', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('nombre_display', sa.String(), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installment_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('monto_total', sa.BigInteger(), nullable=False),
    sa.Column('cuota_actual', sa.Integer(), nullable=False),
    sa.Column('cuotas_totales', sa.Integer(), nullable=False),
    sa.Column('valor_cuota_mensual', sa.BigInteger(), nullable=False),
    sa.Column('tasa', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('ultimos_digitos', sa.String(length=4), nullable=True),
    sa.Column('es_compartido', sa.Boolean(), nullable=False),
    sa.Column('banco', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=False),
    sa.Column('periodo_hasta', sa.Date(), nullable=False),
    sa.Column('deudor_user_id', sa.String(), nullable=False),
    sa.Column('acreedor_user_id', sa.String(), nullable=False),
    sa.Column('monto', sa.BigInteger(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('pagado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['acreedor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deudor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('payment_method_id', sa.String(), nullable=False),
    sa.Column('archivo_origen', sa.String(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=True),
    sa.Column('periodo_hasta', sa.Date(), nullable=True),
    sa.Column('total_facturado_declarado', sa.BigInteger(), nullable=True),
    sa.Column('importado_en', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('patron', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('es_hogar_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('import_batch_id', sa.String(), nullable=True),
    sa.Column('payment_method_id', sa.String(), nullable=False),
    sa.Column('payer_user_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('installment_plan_id', sa.String(), nullable=True),
    sa.Column('fecha_operacion', sa.Date(), nullable=False),
    sa.Column('descripcion_raw', sa.String(), nullable=False),
    sa.Column('descripcion_norm', sa.String(), nullable=False),
    sa.Column('lugar', sa.String(), nullable=True),
    sa.Column('monto', sa.BigInteger(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(), nullable=False),
    sa.Column('es_hogar', sa.Boolean(), nullable=False),
    sa.Column('es_interno', sa.Boolean(), nullable=False),
    sa.Column('hash_dedupe', sa.String(), nullable=False),
    sa.Column('split_override', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('creado_en', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ),
    sa.ForeignKeyConstraint(['installment_plan_id'], ['installment_plans.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('split_allocations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('monto_asignado', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('split_allocations')
    op.drop_table('transactions')
    op.drop_table('merchant_rules')
    op.drop_table('import_batches')
    op.drop_table('settlements')
    op.drop_table('payment_methods')
    op.drop_table('installment_plans')
    op.drop_table('household_members')
    op.drop_table('categories')
    op.drop_table('users')
    op.drop_table('households')
    # ### end Alembic commands ###
